### PR TITLE
update bundler and rubygems

### PR DESCRIPTION
**Pull request by lamont-granquist**
i believe this'll fail on travis...

### CODE REVIEW

**Comment by coderanger** [comment]
What's the goal? Halite depends on Bundler so if there is a specific version I should depend on it directly.

**Comment by lamont-granquist** [comment]
Yeah, it looks like halite isn't compatible with the latest bundler+rubygems -- this is failing in travis...

There's an override in the chef/chef tests that have been making it pass by keeping the default travis versions, but i need to bump that to 1.10.0 or later for the gem metadata stuff and add a chef runtime dep on bundler now...

**Comment by coderanger** [comment]
Got it, thanky :)

**Comment by coderanger** [comment]
Hmm, the only test that is failing is a failure of the test harness, not Halite itself. Will have to dig in a bit.

**Comment by lamont-granquist** [comment]
:+1:

**Comment by coderanger** [comment]
Testing against multiple bundler/rubygems versions is complicated by the fact that env vars are not part of the travis cache key still (I think).

**Comment by lamont-granquist** [comment]
Yeah chef/chef is running against the latest versions for most of the tests, except for a couple where they got overridden either accidentally or like with halite it looks like it was done on purpose.  I'll have to change it so we're running against latest for all the chef/chef travis tests...  Probably halite and friends should test against latest as well...

**Comment by coderanger** [comment]
Running with the Rubygems that comes out of the box is a feature, so I'll have to add specific tests to the matrix for this.

**Pull request closed without merging**
